// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PharmacySystemApi_Id1.proto

package com.example.protos;

public interface FindDrugRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FindDrugRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string apiKey = 1;</code>
   * @return The apiKey.
   */
  java.lang.String getApiKey();
  /**
   * <code>string apiKey = 1;</code>
   * @return The bytes for apiKey.
   */
  com.google.protobuf.ByteString
      getApiKeyBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
